FROM python:3.9-slim-bullseye
# intall ffmpeg
RUN apt-get update && apt-get install -y ffmpeg

WORKDIR /app

COPY requirements.txt .

# upgrade pip
RUN pip install --upgrade pip

# installer les dependances
RUN pip install -r requirements.txt

RUN rm requirements.txt

COPY . .

EXPOSE 8000

# lancer l'application
CMD ["uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
