FROM python:3.8.19-bullseye

# intall ffmpeg
RUN apt-get update && apt-get install -y ffmpeg

WORKDIR /app

COPY . .

# upgrade pip
RUN pip install --upgrade pip

# installer les dependances
RUN pip install -r requirements.txt

EXPOSE 8000

# lancer l'application
CMD ["uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
