FROM python:3.8.19-bullseye

WORKDIR /app

COPY . .

# upgrade pip
RUN pip install --upgrade pip

# installer fastapi cli
RUN pip install fastapi[standard]

# installer les dependances
RUN pip install -r requirements.txt

EXPOSE 8000

# lancer l'application
CMD ["fastapi", "run", "src/main.py"]
